version: '3.8'

services:
  pg:
    image: postgres:12.4
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  rails:
    build: ./rails
    env_file: .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails:/app
    ports:
      - '3000:3000'
    depends_on:
      - pg

volumes:
  pg_data:
